# -*- coding: utf-8 -*-
# Copyright (C) 2006 BMS Group Global (<http://www.bmsgroupglobal.com>).
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    'name': 'BMS CPDT',
    'version': '10.0.1.0.0',
    'author': 'BMS Group Global',
    'category': 'BMS Modules',
    'license': 'AGPL-3',
    'website': 'http://www.bmsgroupglobal.com',
    'depends': [
        'base',
        'mail',
        'login_user_detail',
        'product',
        'website',
        'contacts',
        'bms_sms_vnet',
        'website_crm',
        'im_livechat',
        'web_readonly_bypass',
        'auth_signup',
        'auth_signup_verify_email',
        'hr',
        'crm',
        'website_blog',
    ],
    'data': [
        'views/hr_department.xml',
        'data/document_template_category.xml',
        'data/document_template.xml',
        'data/seal_price.xml',
        'data/day_warning_miss_document.xml',
        'data/session_sequence.xml',
        'data/legal_basic_attachment.xml',
        'data/legal_basic.xml',
        'data/website.xml',
        'data/payment_sequence.xml',
        'data/bank_transfer_config.xml',
        'security/e_gov_security.xml',
        'security/ir.model.access.csv',
        'security/record_rules.xml',
        'templates/templates.xml',
        'templates/email_template.xml',
        'templates/sms_template.xml',
        'templates/seal_order_template.xml',

        'wizard/views/wizard_session_idea_box_view.xml',

        'views/bms_idea_box.xml',
        'views/set_calendar.xml',
        'views/bms_document_template_views.xml',
        'views/bms_session_views.xml',
        'views/bms_session_product_views.xml',
        'views/bms_legal_basic_views.xml',
        'views/bms_mail_template_config.xml',
        'views/bms_sms_template_config.xml',
        'views/bms_papers_template_views.xml',
        'report/session_report_view.xml',
        'report/register_report_view.xml',
        'views/bms_document_menu.xml',
        'views/bms_sms_compose_views.xml',
        'views/signup.xml',
        'views/ir_ui_menu.xml',
        'views/bank_transfer_config.xml',

        'wizard/views/wizard_wellcome.xml',

        'templates/payment_page_template.xml',
        'templates/menu_view.xml',
        'templates/homepage_template.xml',
        'templates/noupdate_template.xml',
        'data/user_template.xml',
    ],
    'demo': [
    ],
    'css': [
        'bms_cpdt/static/src/css/home_page_footer.css',
        'bms_cpdt/static/src/css/procedures_categ.css',
        'bms_cpdt/static/src/css/au_gov1.css',
        'bms_cpdt/static/src/css/au_gov2.css',
        'bms_cpdt/static/src/css/au_gov3.css',
        'bms_cpdt/static/src/css/au_gov4.css',
    ],
    'installable': True,
    'auto_install': False,
    'application': True,
}
